server:
  port: 8082

oauth2:
  clientId: modern-renting-client
  clientSecret: "{noop}modern-renting-secret"
  introspectionUri: http://localhost:9000/oauth2/introspect

spring:
  application:
    name: oauth2

