server:
  port: 8082

oauth2:
  clientId: service-client
  clientSecret: "service-secret"
  introspectionUri: http://localhost:9000/oauth2/introspect

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: oauth2
  r2dbc:
    url: r2dbc:h2:file:///./testdb;MODE=PostgreSQL;
    username: postgres
    password: postgres
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:h2:file:./testdb;MODE=PostgreSQL;
    user: postgres
    password: postgres


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-methods: "*"

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    configs:
      default:
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 20
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        register-health-indicator: true
    instances:
      cloudBinderService:
        base-config: default
      signature-service:
        base-config: default
  bulkhead:
    instances:
      binders:
        max-concurrent-calls: 10
      document:
        max-concurrent-calls: 10
