server:
  port: 8082

oauth2:
  clientId: service-client
  clientSecret: "service-secret"
  introspectionUri: http://localhost:9000/oauth2/introspect

spring:
  application:
    name: oauth2

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

