# Redis, Kafka, zooKeeper, Nginx
version: '3'

networks:
  proxy:
    driver: bridge
  backend:
    driver: bridge
  db:
    driver: bridge

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - type: bind
        source: ./create_database.sql
        target: /docker-entrypoint-initdb.d/create_database.sql
    networks:
      - db

  user:
    image: eclipse-temurin:21-jdk
    restart: always
    command: "tail -f /dev/null"
    networks:
      - db
      - backend

  oauth2:
    image: eclipse-temurin:21-jdk
    restart: always
    command: "tail -f /dev/null"
    networks:
      - db
      - backend

  vehicle:
    image: eclipse-temurin:21-jdk
    restart: always
    command: "tail -f /dev/null"
    networks:
      - db
      - backend
