@startuml
skinparam backgroundColor #EEEBDC
skinparam handwritten false
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline

actor User
participant "Frontend App" as Frontend
participant "User Service" as UserService
participant "OAuth2 Server" as OAuth

autonumber 1
User -> Frontend: Log out
activate Frontend

Frontend -> UserService: Log out Request
activate UserService

UserService -> OAuth: POST /oauth/revoke(token)
activate OAuth
OAuth --> UserService: response 200
deactivate OAuth

UserService --> Frontend: response200
deactivate UserService

Frontend --> User: Log out
deactivate Frontend
@enduml