server:
  port: 8081

oauth2:
  clientId: service-client
  clientSecret: "service-secret"
  introspectionUri: http://localhost:9000/oauth2/introspect

spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      path: /h2-console
      enabled: true

  application:
    name: oauth2
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/db.changelog-master.xml

