server:
  port: 8080

oauth2:
  clientId: service-client
  clientSecret: "service-secret"
  introspectionUri: http://oauth2:8080/oauth2/introspect

spring:
  config:
    activate:
      on-profile: docker
  application:
    name: oauth2
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  liquibase:
    contexts: docker
    change-log: classpath:db/changelog/db.changelog-master.xml