server:
  port: 8081

oauth2:
  clientId: modern-renting-client
  clientSecret: "modern-renting-secret"
  introspectionUri: http://localhost:9000/oauth2/introspect
  tokenUri: http://localhost:9000/oauth2/token

spring:
  application:
    name: oauth2

