server:
  port: 8080

oauth2:
  clientId: modern-renting-client
  clientSecret: "{noop}modern-renting-secret"
  svcClientId: service-client
  svcClientSecret: "{noop}service-secret"

spring:
  config:
    activate:
      on-profile: docker
  application:
    name: oauth2
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  liquibase:
    contexts: docker
    change-log: classpath:db/changelog/db.changelog-master.xml
    url:  jdbc:postgresql://postgres:5432/userdb
    user: postgres
    password: postgres

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
